### ISSUE TITLE
Support for unicode parsing

### ISSUE THREAD

**Issue by brianmmorton** [FWeinb/node-osascript#9]
Hey! Awesome library. You wrote a lot of code to get this to work, stoked that i am able to benefit from it. 

I am struggling with unicode parsing. Looks like when the library encounters a unicode symbol it just returns "{"... not sure why. 

Any ideas or insights on this? 

Thanks in advance

**Comment by FWeinb** [comment]
Do you have a code example that I could use to debug this?

**Comment by rbrtrbrt** [comment]
I had a unicode problem when the osa-parser parsed this string: 

`{ {  t:"docopt—language for description of command-line interfaces", d:date "Tuesday 16 September 2014 at 13:11:10", u:"http://docopt.org/" }, {  t: "Alloy", d:date "Tuesday 16 September 2014 at 13:08:32", u:"http://alloy.mit.edu/alloy/index.html" } }`

It's the dash in the first title: `docopt—language` that caused the problem.

I'm not familiar enough with Grunt or PEG to quickly do a fork and create a pull-request, but looking at `osa-parser.js`, it turns out that a regex created on line 123:
` peg$c74 = /^[\n\t -!#-[\]-\u10FFFF]/,` is not a correct Javascript regular expression: high/large unicode characters should be written (according to [MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Guide/Regular_Expressions#special-unicode-escape-es6) as `\u{hhhhhh}`, and the 'u' flag should be set. 

So i replaced lines 123 and 124 with these:
```js
        peg$c74 = /^[\n\t\x20-\x21\x23-\x5B\x5D-\u{10FFFF}]/u,
        peg$c75 = { type: "class", value: "[\\n\\t\x20-\\x21\\x23-\\x5B\\x5D-\\u{10FFFF}]", description: "[\\n\\t\x20-\\x21\\x23-\\x5B\\x5D-\\u{10FFFF}]" },
```
and my problem went away.

I hope this helps, sorry for not submitting a proper pull-request.

**Comment by FWeinb** [comment]
I just upgrade to the latest version of `pegjs@0.10.0`. And did some much needed cleanup for this library. I would really appreciate it if you could give `node-osascript@2.0.0` a try and report back if it fixed your issue.

**Comment by rbrtrbrt** [comment]
Version 2.0.0 did indeed solve my unicode problem. Thank you!

**Comment by FWeinb** [comment]
Thanks for testing!
